# -*- coding: utf-8 -*-
"""Untitled49.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KNKsnZKGKzW04ZAucgvprXdMTpEdrewO
"""

from transformers import pipeline

pipe = pipeline("image-classification", model="joseluhf11/sign_language_classification")

from transformers import AutoImageProcessor, AutoModelForImageClassification

processor = AutoImageProcessor.from_pretrained("joseluhf11/sign_language_classification")
model = AutoModelForImageClassification.from_pretrained("joseluhf11/sign_language_classification")

from transformers import AutoImageProcessor, ViTForImageClassification
import torch
from PIL import Image

image = Image.open("l.jpg")

inputs = processor(images = image, return_tensors="pt")

with torch.no_grad():
    logits = model(**inputs).logits

# model predicts one of the 1000 ImageNet classes
predicted_label = logits.argmax(-1).item()
print(model.config.id2label[predicted_label])